/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedWatchEpisodeIdRouteImport } from './routes/_authenticated/watch.$episodeId'
import { Route as AuthenticatedSeriesIdRouteImport } from './routes/_authenticated/series.$id'
import { Route as AuthenticatedBrowseTypeRouteImport } from './routes/_authenticated/browse.$type'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWatchEpisodeIdRoute =
  AuthenticatedWatchEpisodeIdRouteImport.update({
    id: '/watch/$episodeId',
    path: '/watch/$episodeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeriesIdRoute = AuthenticatedSeriesIdRouteImport.update({
  id: '/series/$id',
  path: '/series/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrowseTypeRoute = AuthenticatedBrowseTypeRouteImport.update({
  id: '/browse/$type',
  path: '/browse/$type',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/home': typeof AuthenticatedHomeRoute
  '/search': typeof AuthenticatedSearchRoute
  '/browse/$type': typeof AuthenticatedBrowseTypeRoute
  '/series/$id': typeof AuthenticatedSeriesIdRoute
  '/watch/$episodeId': typeof AuthenticatedWatchEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/home': typeof AuthenticatedHomeRoute
  '/search': typeof AuthenticatedSearchRoute
  '/browse/$type': typeof AuthenticatedBrowseTypeRoute
  '/series/$id': typeof AuthenticatedSeriesIdRoute
  '/watch/$episodeId': typeof AuthenticatedWatchEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/browse/$type': typeof AuthenticatedBrowseTypeRoute
  '/_authenticated/series/$id': typeof AuthenticatedSeriesIdRoute
  '/_authenticated/watch/$episodeId': typeof AuthenticatedWatchEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/home'
    | '/search'
    | '/browse/$type'
    | '/series/$id'
    | '/watch/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/home'
    | '/search'
    | '/browse/$type'
    | '/series/$id'
    | '/watch/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/home'
    | '/_authenticated/search'
    | '/_authenticated/browse/$type'
    | '/_authenticated/series/$id'
    | '/_authenticated/watch/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watch/$episodeId': {
      id: '/_authenticated/watch/$episodeId'
      path: '/watch/$episodeId'
      fullPath: '/watch/$episodeId'
      preLoaderRoute: typeof AuthenticatedWatchEpisodeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/series/$id': {
      id: '/_authenticated/series/$id'
      path: '/series/$id'
      fullPath: '/series/$id'
      preLoaderRoute: typeof AuthenticatedSeriesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/browse/$type': {
      id: '/_authenticated/browse/$type'
      path: '/browse/$type'
      fullPath: '/browse/$type'
      preLoaderRoute: typeof AuthenticatedBrowseTypeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedBrowseTypeRoute: typeof AuthenticatedBrowseTypeRoute
  AuthenticatedSeriesIdRoute: typeof AuthenticatedSeriesIdRoute
  AuthenticatedWatchEpisodeIdRoute: typeof AuthenticatedWatchEpisodeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedBrowseTypeRoute: AuthenticatedBrowseTypeRoute,
  AuthenticatedSeriesIdRoute: AuthenticatedSeriesIdRoute,
  AuthenticatedWatchEpisodeIdRoute: AuthenticatedWatchEpisodeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
